version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Lima"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"
      testing:
        patterns:
          - "vitest*"
          - "@vitest/*"
          - "@testing-library/*"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Lima"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
