/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TallerRouteImport } from './routes/taller'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlmacenRouteImport } from './routes/almacen'
import { Route as IndexRouteImport } from './routes/index'

const TallerRoute = TallerRouteImport.update({
  id: '/taller',
  path: '/taller',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmacenRoute = AlmacenRouteImport.update({
  id: '/almacen',
  path: '/almacen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/almacen': typeof AlmacenRoute
  '/analytics': typeof AnalyticsRoute
  '/catalogo': typeof CatalogoRoute
  '/taller': typeof TallerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/almacen': typeof AlmacenRoute
  '/analytics': typeof AnalyticsRoute
  '/catalogo': typeof CatalogoRoute
  '/taller': typeof TallerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/almacen': typeof AlmacenRoute
  '/analytics': typeof AnalyticsRoute
  '/catalogo': typeof CatalogoRoute
  '/taller': typeof TallerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/almacen' | '/analytics' | '/catalogo' | '/taller'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/almacen' | '/analytics' | '/catalogo' | '/taller'
  id: '__root__' | '/' | '/almacen' | '/analytics' | '/catalogo' | '/taller'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlmacenRoute: typeof AlmacenRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CatalogoRoute: typeof CatalogoRoute
  TallerRoute: typeof TallerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/taller': {
      id: '/taller'
      path: '/taller'
      fullPath: '/taller'
      preLoaderRoute: typeof TallerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almacen': {
      id: '/almacen'
      path: '/almacen'
      fullPath: '/almacen'
      preLoaderRoute: typeof AlmacenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlmacenRoute: AlmacenRoute,
  AnalyticsRoute: AnalyticsRoute,
  CatalogoRoute: CatalogoRoute,
  TallerRoute: TallerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
